apiVersion: apps/v1
kind: Deployment
metadata:
  name: nearr27
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nearr27
  template:
    metadata:
      labels:
        app: nearr27
    spec:
      containers:
      - image: okteto.dev/nearr27:latest
        name: nearr27
        envFrom:
        - configMapRef:
            name: nearr27-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: nearr27
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "nearr27"
    port: 8080
  selector:
    app: nearr27
